/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AboutRouteImport } from './routes/about'
import { Route as BphHolepRouteImport } from './routes/bph-holep'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as FemaleUrologyRouteImport } from './routes/female-urology'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as KidneyStonesRouteImport } from './routes/kidney-stones'
import { Route as MaleUrologyRouteImport } from './routes/male-urology'
import { Route as PatientEducationRouteImport } from './routes/patient-education'
import { Route as PelvicReconstructionRouteImport } from './routes/pelvic-reconstruction'
import { Route as ReviewsRouteImport } from './routes/reviews'
import { Route as SecondOpinionsRouteImport } from './routes/second-opinions'
import { Route as VoidingDysfunctionRouteImport } from './routes/voiding-dysfunction'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const BphHolepRoute = BphHolepRouteImport.update({
  id: '/bph-holep',
  path: '/bph-holep',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const FemaleUrologyRoute = FemaleUrologyRouteImport.update({
  id: '/female-urology',
  path: '/female-urology',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const KidneyStonesRoute = KidneyStonesRouteImport.update({
  id: '/kidney-stones',
  path: '/kidney-stones',
  getParentRoute: () => rootRouteImport,
} as any)
const MaleUrologyRoute = MaleUrologyRouteImport.update({
  id: '/male-urology',
  path: '/male-urology',
  getParentRoute: () => rootRouteImport,
} as any)
const PatientEducationRoute = PatientEducationRouteImport.update({
  id: '/patient-education',
  path: '/patient-education',
  getParentRoute: () => rootRouteImport,
} as any)
const PelvicReconstructionRoute = PelvicReconstructionRouteImport.update({
  id: '/pelvic-reconstruction',
  path: '/pelvic-reconstruction',
  getParentRoute: () => rootRouteImport,
} as any)
const ReviewsRoute = ReviewsRouteImport.update({
  id: '/reviews',
  path: '/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const SecondOpinionsRoute = SecondOpinionsRouteImport.update({
  id: '/second-opinions',
  path: '/second-opinions',
  getParentRoute: () => rootRouteImport,
} as any)
const VoidingDysfunctionRoute = VoidingDysfunctionRouteImport.update({
  id: '/voiding-dysfunction',
  path: '/voiding-dysfunction',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bph-holep': typeof BphHolepRoute
  '/contact': typeof ContactRoute
  '/female-urology': typeof FemaleUrologyRoute
  '/insurance': typeof InsuranceRoute
  '/kidney-stones': typeof KidneyStonesRoute
  '/male-urology': typeof MaleUrologyRoute
  '/patient-education': typeof PatientEducationRoute
  '/pelvic-reconstruction': typeof PelvicReconstructionRoute
  '/reviews': typeof ReviewsRoute
  '/second-opinions': typeof SecondOpinionsRoute
  '/voiding-dysfunction': typeof VoidingDysfunctionRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bph-holep': typeof BphHolepRoute
  '/contact': typeof ContactRoute
  '/female-urology': typeof FemaleUrologyRoute
  '/insurance': typeof InsuranceRoute
  '/kidney-stones': typeof KidneyStonesRoute
  '/male-urology': typeof MaleUrologyRoute
  '/patient-education': typeof PatientEducationRoute
  '/pelvic-reconstruction': typeof PelvicReconstructionRoute
  '/reviews': typeof ReviewsRoute
  '/second-opinions': typeof SecondOpinionsRoute
  '/voiding-dysfunction': typeof VoidingDysfunctionRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/bph-holep': typeof BphHolepRoute
  '/contact': typeof ContactRoute
  '/female-urology': typeof FemaleUrologyRoute
  '/insurance': typeof InsuranceRoute
  '/kidney-stones': typeof KidneyStonesRoute
  '/male-urology': typeof MaleUrologyRoute
  '/patient-education': typeof PatientEducationRoute
  '/pelvic-reconstruction': typeof PelvicReconstructionRoute
  '/reviews': typeof ReviewsRoute
  '/second-opinions': typeof SecondOpinionsRoute
  '/voiding-dysfunction': typeof VoidingDysfunctionRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/bph-holep'
    | '/contact'
    | '/female-urology'
    | '/insurance'
    | '/kidney-stones'
    | '/male-urology'
    | '/patient-education'
    | '/pelvic-reconstruction'
    | '/reviews'
    | '/second-opinions'
    | '/voiding-dysfunction'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/bph-holep'
    | '/contact'
    | '/female-urology'
    | '/insurance'
    | '/kidney-stones'
    | '/male-urology'
    | '/patient-education'
    | '/pelvic-reconstruction'
    | '/reviews'
    | '/second-opinions'
    | '/voiding-dysfunction'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/bph-holep'
    | '/contact'
    | '/female-urology'
    | '/insurance'
    | '/kidney-stones'
    | '/male-urology'
    | '/patient-education'
    | '/pelvic-reconstruction'
    | '/reviews'
    | '/second-opinions'
    | '/voiding-dysfunction'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  BphHolepRoute: typeof BphHolepRoute
  ContactRoute: typeof ContactRoute
  FemaleUrologyRoute: typeof FemaleUrologyRoute
  InsuranceRoute: typeof InsuranceRoute
  KidneyStonesRoute: typeof KidneyStonesRoute
  MaleUrologyRoute: typeof MaleUrologyRoute
  PatientEducationRoute: typeof PatientEducationRoute
  PelvicReconstructionRoute: typeof PelvicReconstructionRoute
  ReviewsRoute: typeof ReviewsRoute
  SecondOpinionsRoute: typeof SecondOpinionsRoute
  VoidingDysfunctionRoute: typeof VoidingDysfunctionRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bph-holep': {
      id: '/bph-holep'
      path: '/bph-holep'
      fullPath: '/bph-holep'
      preLoaderRoute: typeof BphHolepRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/female-urology': {
      id: '/female-urology'
      path: '/female-urology'
      fullPath: '/female-urology'
      preLoaderRoute: typeof FemaleUrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/kidney-stones': {
      id: '/kidney-stones'
      path: '/kidney-stones'
      fullPath: '/kidney-stones'
      preLoaderRoute: typeof KidneyStonesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/male-urology': {
      id: '/male-urology'
      path: '/male-urology'
      fullPath: '/male-urology'
      preLoaderRoute: typeof MaleUrologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/patient-education': {
      id: '/patient-education'
      path: '/patient-education'
      fullPath: '/patient-education'
      preLoaderRoute: typeof PatientEducationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pelvic-reconstruction': {
      id: '/pelvic-reconstruction'
      path: '/pelvic-reconstruction'
      fullPath: '/pelvic-reconstruction'
      preLoaderRoute: typeof PelvicReconstructionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reviews': {
      id: '/reviews'
      path: '/reviews'
      fullPath: '/reviews'
      preLoaderRoute: typeof ReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/second-opinions': {
      id: '/second-opinions'
      path: '/second-opinions'
      fullPath: '/second-opinions'
      preLoaderRoute: typeof SecondOpinionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/voiding-dysfunction': {
      id: '/voiding-dysfunction'
      path: '/voiding-dysfunction'
      fullPath: '/voiding-dysfunction'
      preLoaderRoute: typeof VoidingDysfunctionRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  BphHolepRoute: BphHolepRoute,
  ContactRoute: ContactRoute,
  FemaleUrologyRoute: FemaleUrologyRoute,
  InsuranceRoute: InsuranceRoute,
  KidneyStonesRoute: KidneyStonesRoute,
  MaleUrologyRoute: MaleUrologyRoute,
  PatientEducationRoute: PatientEducationRoute,
  PelvicReconstructionRoute: PelvicReconstructionRoute,
  ReviewsRoute: ReviewsRoute,
  SecondOpinionsRoute: SecondOpinionsRoute,
  VoidingDysfunctionRoute: VoidingDysfunctionRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
